dump_dir: <full path to copy current codebase to>
name: "debug"
steps: 2000
probe_freq: 100
seed: 777
optim:
  lr: 3e-4
  warmup: 2000
  lr_min_ratio: 0.000001
  clip: 10.0

distributed:
  fsdp_type: full_shard
  # fsdp_type: no_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1 # number of tensor parallel (Megatron equavalent)
  # dp_shard: 4 # number of model shard (Number of GPUs in one node)
  # dp_replicate: 4 # number of data parallel copy (Number of nodes in training run)

model:
  dim: 2048
  n_layers: 25
  n_heads: 16

data:
  root_dir: <full path that store data folder = [ABSOLUTE_PATH_CURRENT_DIR]/data>
  sources:
    fineweb_edu_10bt_shuffled: 1.0
  batch_size: 4
  prefetch_size: 1024
  seq_len: 2048
  n_views: 2
  load_async: true
  tokenizer:
    name: bytes
    path: <full path of tokenizer.model>

profiling:
  run: true

checkpoint:
  dump:
    every: 100
    keep: 1
  eval:
    every: 100
    keep: 1

logging:
  freq: 10
eval:
  generator:
    max_tokens: 8192
    max_tokens: 8192
    dtype: bf16
    temperature: 1.0
    top_p: 0.95
  harness:
    tasks:
      - task: piqa
        dataset_path: <full path to piqa>
      - task: nq_open
        dataset_path: <full path to nq_open>
        num_fewshot: 5
      - task: hellaswag
        dataset_path: <full path to hellaswag>
